# version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: authpass
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U authuser -d auth_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  # auth-service:
  #   build: .
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     DATABASE_URL: postgresql://authuser:authpass@db:5432/auth_db
  #     SECRET_KEY: your-super-secret-key-change-in-production-min-32-chars
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   volumes:
  #     - ./app:/app/app
  #   command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data: